name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cicd-tutorial:${{ github.sha }} .

      - name: Run tests in container
        run: docker run cicd-tutorial:${{ github.sha }} npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          docker tag cicd-tutorial:${{ github.sha }} enxan/cicd-tutorial:latest
          docker push enxan/cicd-tutorial:latest

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull enxan/cicd-tutorial:latest
            docker stop cicd-tutorial || true
            docker rm cicd-tutorial || true
            docker run -d --name cicd-tutorial -p 80:80 enxan/cicd-tutorial:latest
